apiVersion: v1
kind: Service
metadata:
  name: order
  namespace: default
  labels:
    app: order
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081
  selector:
    app: order
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  labels:
    app: order
  namespace: default
spec:
  selector:
    matchLabels:
      app: order
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - image: simas/order:7
          name: order
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: CATALOG_URL
              value: "http://catalog:8080"
          resources:
            requests:
              memory: "512M"
              cpu: "200m"
            limits:
              memory: "1G"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10